//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Color { get; set; }
        public string Country { get; set; }
        public int Quantity { get; set; }
        public string ManufactureId { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }

        public override string ToString()
        {
            return ID.ToString() + " " + Name.ToString() + " " + Price.ToString() + " " + Color.ToString() + " " + Country.ToString() + " " + Quantity.ToString();
        }
    }
}
